name: StartupSwipe
targets:
  StartupSwipe:
    type: application
    platform: iOS
    deploymentTarget: 17.0
    sources:
      - path: Sources/StartupSwipe
    resources:
      - path: Resources
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.example.StartupSwipe
      SWIFT_VERSION: 5.10
      INFOPLIST_FILE: Resources/Info.plist
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    postBuildScripts: []
    preBuildScripts: []
